apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: server
          image: server
          ports:
            - name: server-port
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
